version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: traker_psg_db
    environment:
      POSTGRES_DB: jobtraker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
