version: '3'

services:
  app:
    build: .
    container_name: job-tracker-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    environment:
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: Admin_123
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_NAME: jobtraker_new
      SECRET_KEY: asdfa#s&*^&asd9f
      ALGORITHM: HS512
      ACCESS_TOKEN_EXPIRE_MINUTES: 25


  postgres_db:
    image: postgres:latest
    container_name: traker_psg_db
    environment:
      POSTGRES_DB: jobtraker
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Admin_123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
